---
- name: creer een test user
  hosts: "{{ naam }}" 
  remote_user: ansusr
  become: true
  become_user: root
  become_method: sudo
  tasks:
    ansible.builtin.user:
    name: "{{ gebruiker }}"
    shell: /bin/bash
    comment: testgebruiker 
    groups: ['staff','users']
    home: /home/{{ gebruiker }}
    


