---
- name: creer een test user
  hosts: "{{ naam }}" 
  remote_user: ansusr
  become: true
  become_user: root
  become_method: sudo
  roles:
    - name: users
      user:
        - username: "{{ gebruiker }}"      
          name: testgebruiker 
          groups: ['staff','users']
          home: /home/{{ gebruiker }}
    


