---
- name: creer een test user
  hosts: ceres
  remote_user: ansusr
  become: true
  become_user: root
  become_method: sudo
  tasks:
  - user:
     name: genrtp
     state: absent
     remove: yes    


